"""add expenses and income tables

Revision ID: fe68ad95c68f
Revises: 35c594a1837d
Create Date: 2026-07-17 15:41:49.388865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe68ad95c68f'
down_revision: Union[str, Sequence[str], None] = '35c594a1837d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'GROCERY', 'FUEL', 'SHOPPING', 'BILLS', 'HEALTH', 'ENTERTAINMENT', 'TRAVEL', 'EDUCATION', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('account', sa.Enum('CASH', 'UPI', 'BANK', name='accounttype'), nullable=False),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.Enum('SALARY', 'INVESTMENT', 'OTHER', name='incomecategory'), nullable=False),
    sa.Column('account', sa.Enum('CASH', 'UPI', 'BANK', name='accounttype'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_user_id'), 'income', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_user_id'), table_name='income')
    op.drop_table('income')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
